### ISSUE TITLE
1.21.x

### ISSUE THREAD

**Issue by ghost** [Gauraaaaaaaa/RankingOfThings#2]
Are you planned this ?

**Comment by Gauraaaaaaaa** [comment]
Hi!

Yes, it is planned!

Next release should be it.

**Comment by ghost** [comment]
Nice !

**Comment by Gauraaaaaaaa** [comment]
1.21.x version is finally out !

**Comment by ghost** [comment]
Thanks !(I was the first download)Le 20 sept. 2024 à 15:01, Gaura ***@***.***> a écrit :﻿
1.21.x version is finally out !
